name: Node.js Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies (Node 6)
      if: matrix.node-version == '6.x'
      run: npm install
      
    - name: Install dependencies (Node 20)
      if: matrix.node-version == '20.x'
      run: npm ci
      
    - name: Run tests
      run: npm test
